### PR TITLE
Update test-cing-dev.txt

### PR DESCRIPTION
**Pull request by chiendm**

### CODE REVIEW

**Comment by gdgate** [comment]
Build failed (check pipeline).

- Test-zuul-cloner-cing : NOT_REGISTERED

**Comment by chiendm** [comment]
ok to test

**Comment by gdgate** [comment]
Build failed (check pipeline).

- Test-zuul-cloner-cing : NOT_REGISTERED

**Comment by chiendm** [comment]
ok to test

**Comment by gdgate** [comment]
Build failed (check pipeline).

- Test-zuul-cloner-cing : NOT_REGISTERED

**Comment by chiendm** [comment]
ok to test

**Comment by gdgate** [comment]
Build failed (check pipeline).

- Test-zuul-cloner-cing : NOT_REGISTERED

**Comment by chiendm** [comment]
ok to test

**Comment by gdgate** [comment]
Build succeeded (check pipeline).

- https://cing-dev.intgdc.com/job/Test-zuul-cloner-cing/2/ : SUCCESS in 0s

**Comment by gdgate** [comment]
Build succeeded (check pipeline).

- https://cing-dev.intgdc.com/job/Test-zuul-cloner-cing/3/ : SUCCESS in 0s

**Pull request closed without merging**
