### PR TITLE
DC-1572: Update license - just a dummy PR

### PR DESCRIPTION
**Pull request by caohhung**

### CODE REVIEW

**Comment by gdgate** [comment]
Build succeeded (check pipeline).

**Comment by gdgate** [comment]
Build succeeded (check pipeline).

**Comment by gdgate** [comment]
Build failed (check pipeline).

- https://cing-dev.intgdc.com/job/compliance/job/Test-zuul-cloner-cing/1/ : FAILURE in 0s

**Comment by caohhung** [comment]
ok to test

**Comment by gdgate** [comment]
Build failed (check pipeline).

- https://cing-dev.intgdc.com/job/compliance/job/Test-zuul-cloner-cing/1/ : FAILURE in 14s

**Comment by caohhung** [comment]
ok to test

**Comment by gdgate** [comment]
Build failed (check pipeline).

- https://cing-dev.intgdc.com/job/compliance/job/Test-zuul-cloner-cing/1/ : FAILURE in 4s

**Comment by gdgate** [comment]
Build failed (check pipeline).

- https://cing-dev.intgdc.com/job/compliance/job/Test-zuul-cloner-cing/4/ : FAILURE in 4s

**Comment by caohhung** [comment]
ok to test

**Comment by gdgate** [comment]
Build failed (check pipeline).

- https://cing-dev.intgdc.com/job/compliance/job/Test-zuul-cloner-cing/6/ : FAILURE in 15s

**Pull request closed without merging**
