### PR TITLE
dummy PR

### PR DESCRIPTION
**Pull request by caohhung**

### CODE REVIEW

**Comment by gdgate** [comment]
Build failed (check pipeline).

- Test-zuul-cloner-cing : NOT_REGISTERED

**Comment by caohhung** [comment]
ok to test

**Comment by gdgate** [comment]
Build failed (check pipeline).

- Test-zuul-cloner-cing : NOT_REGISTERED

**Comment by caohhung** [comment]
ok to test

**Comment by gdgate** [comment]
Build failed (check pipeline).

- Test-zuul-cloner-cing : NOT_REGISTERED

**Comment by caohhung** [comment]
ok to test

**Comment by gdgate** [comment]
Build failed (check pipeline).

- Test-zuul-cloner-cing : NOT_REGISTERED

**Comment by gdgate** [comment]
Build failed (check pipeline).

- Test-zuul-cloner-cing : NOT_REGISTERED

**Comment by gdgate** [comment]
Build succeeded (check pipeline).

- https://cing-dev.intgdc.com/job/Test-zuul-cloner-cing/1/ : SUCCESS in 1s

**Pull request closed without merging**
