### PR TITLE
Testing PR

### PR DESCRIPTION
**Pull request by yenkins**

### CODE REVIEW

**Comment by janpriessnitz** [comment]
ok to test

**Comment by janpriessnitz** [comment]
ok to test

**Comment by janpriessnitz** [comment]
ok to test

**Comment by janpriessnitz** [comment]
ok to test

**Comment by janpriessnitz** [comment]
ok to test

**Comment by janpriessnitz** [comment]
ok to test

**Comment by janpriessnitz** [comment]
ok to test

**Comment by janpriessnitz** [comment]
ok to test

**Comment by janpriessnitz** [comment]
ok to test

**Comment by gdgate** [comment]
Build failed (check pipeline).

- Test-zuul-cloner : NOT_REGISTERED

**Comment by janpriessnitz** [comment]
ok to test

**Comment by gdgate** [comment]
Build failed (check pipeline).

- Test-zuul-cloner : NOT_REGISTERED

**Comment by janpriessnitz** [comment]
ok to test

**Comment by gdgate** [comment]
Build failed (check pipeline).

- Test-zuul-cloner : NOT_REGISTERED

**Comment by janpriessnitz** [comment]
ok to test

**Comment by gdgate** [comment]
Build failed (check pipeline).

- Test-zuul-cloner : NOT_REGISTERED

**Comment by janpriessnitz** [comment]
ok to test

**Comment by gdgate** [comment]
Build failed (check pipeline).

- Test-zuul-cloner : NOT_REGISTERED

**Comment by janpriessnitz** [comment]
ok to test

**Comment by gdgate** [comment]
Build succeeded (check pipeline).

- http://ci-dev.intgdc.com/job/Test-zuul-cloner/2/ : SUCCESS in 3s

**Pull request closed without merging**
