### PR TITLE
test-abc

### PR DESCRIPTION
**Pull request by caohhung**

### CODE REVIEW

**Comment by gdgate** [comment]
Build succeeded (check pipeline).

**Comment by gdgate** [comment]
Build failed (check pipeline).

- Test-zuul-cloner-cing : NOT_REGISTERED

**Comment by caohhung** [comment]
ok to test

**Comment by gdgate** [comment]
Build succeeded (check pipeline).

- https://cing-dev.intgdc.com/job/Test-zuul-cloner-cing/1/ : SUCCESS in 1s

**Comment by gdgate** [comment]
Build succeeded (check pipeline).

- https://cing-dev.intgdc.com/job/Test-zuul-cloner-cing/2/ : SUCCESS in 1s

**Comment by caohhung** [comment]
ok to test

**Comment by gdgate** [comment]
Build succeeded (check pipeline).

- https://cing-dev.intgdc.com/job/Test-zuul-cloner-cing/3/ : SUCCESS in 1s

**Comment by gdgate** [comment]
Build succeeded (check pipeline).

- https://cing-dev.intgdc.com/job/Test-zuul-cloner-cing/4/ : SUCCESS in 1s

**Pull request merged**
