### PR TITLE
PR A

### PR DESCRIPTION
**Pull request by chiendm**

### CODE REVIEW

**Comment by chiendm** [comment]
ok to test

**Comment by gdgate** [comment]
Build succeeded (check pipeline).

**Comment by chiendm** [comment]
ok to test

**Comment by gdgate** [comment]
Build succeeded (check pipeline).

**Comment by helobinvn** [comment]
ok to test

**Comment by gdgate** [comment]
Build succeeded (check pipeline).

**Comment by chiendm** [comment]
ok to test

**Comment by gdgate** [comment]
Build succeeded (check pipeline).

- https://cing-dev.intgdc.com/job/ci/job/update-ci-infra-local-repo/8/ : SUCCESS in 16m 41s

**Comment by chiendm** [comment]
ok to test

**Comment by gdgate** [comment]
Build succeeded (check pipeline).

- https://cing-dev.intgdc.com/job/ci/job/update-ci-infra-local-repo/10/ : SUCCESS in 16m 42s

**Comment by chiendm** [comment]
ok to test

**Comment by gdgate** [comment]
Build failed (check pipeline).

- https://cing-dev.intgdc.com/job/ci/job/update-ci-infra-local-repo/13/ : ABORTED in 14m 16s

**Comment by chiendm** [comment]
ok to test

**Comment by gdgate** [comment]
Build failed (check pipeline).

- https://cing-dev.intgdc.com/job/ci/job/update-ci-infra-local-repo/15/ : ABORTED in 33s

**Comment by chiendm** [comment]
ok to test

**Comment by gdgate** [comment]
Build failed (check pipeline).

- https://cing-dev.intgdc.com/job/ci/job/update-ci-infra-local-repo/19/ : ABORTED in 7s

**Comment by chiendm** [comment]
ok to test

**Comment by gdgate** [comment]
Build failed (check pipeline).

- https://cing-dev.intgdc.com/job/ci/job/update-ci-infra-local-repo/21/ : ABORTED in 2m 14s

**Comment by chiendm** [comment]
ok to test

**Comment by gdgate** [comment]
Build succeeded (check pipeline).

- https://cing-dev.intgdc.com/job/ci/job/update-ci-infra-local-repo/26/ : SUCCESS in 16m 42s

**Comment by chiendm** [comment]
ok to test

**Comment by gdgate** [comment]
Build failed (check pipeline).

- https://cing-dev.intgdc.com/job/ci/job/update-ci-infra-local-repo/28/ : ABORTED in 1m 17s

**Comment by chiendm** [comment]
ok to test

**Comment by gdgate** [comment]
Build failed (check pipeline).

- https://cing-dev.intgdc.com/job/ci/job/update-ci-infra-local-repo/31/ : ABORTED in 1m 04s

**Comment by chiendm** [comment]
ok to test

**Comment by gdgate** [comment]
Build failed (check pipeline).

- https://cing-dev.intgdc.com/job/ci/job/update-ci-infra-local-repo/34/ : ABORTED in 1m 43s

**Comment by chiendm** [comment]
ok to test

**Comment by gdgate** [comment]
Build succeeded (check pipeline).

- https://cing-dev.intgdc.com/job/ci/job/update-ci-infra-local-repo/37/ : SUCCESS in 16m 41s

**Comment by chiendm** [comment]
ok to test

**Comment by chiendm** [comment]
ok to test

**Comment by gdgate** [comment]
Build succeeded (check pipeline).

- https://cing-dev.intgdc.com/job/ci/job/update-ci-infra-local-repo/44/ : SUCCESS in 16m 41s

**Comment by gdgate** [comment]
Build succeeded (check pipeline).

- https://cing-dev.intgdc.com/job/ci/job/update-ci-infra-local-repo/47/ : SUCCESS in 16m 41s

**Comment by chiendm** [comment]
ok to test

**Comment by gdgate** [comment]
Build succeeded (check pipeline).

**Comment by chiendm** [comment]
ok to test

**Comment by gdgate** [comment]
Build succeeded (check pipeline).

**Comment by helobinvn** [comment]
ok to test

**Comment by gdgate** [comment]
Build succeeded (check pipeline).

**Comment by helobinvn** [comment]
ok to test

**Comment by gdgate** [comment]
Build failed (check pipeline).

- https://cing-dev.intgdc.com/job/ci/job/update-ci-infra-local-repo/53/ : ABORTED in 4m 35s

**Comment by helobinvn** [comment]
ok to test

**Comment by gdgate** [comment]
Build failed (check pipeline).

- https://cing-dev.intgdc.com/job/ci/job/update-ci-infra-local-repo/59/ : ABORTED in 26s

**Comment by helobinvn** [comment]
ok to test

**Comment by gdgate** [comment]
Build failed (check pipeline).

- https://cing-dev.intgdc.com/job/ci/job/update-ci-infra-local-repo/60/ : ABORTED in 2m 34s

**Comment by helobinvn** [comment]
ok to test

**Comment by gdgate** [comment]
Build failed (check pipeline).

- https://cing-dev.intgdc.com/job/ci/job/update-ci-infra-local-repo/66/ : ABORTED in 5s

**Comment by helobinvn** [comment]
ok to test

**Comment by gdgate** [comment]
Build failed (check pipeline).

- https://cing-dev.intgdc.com/job/ci/job/update-ci-infra-local-repo/70/ : ABORTED in 7m 20s

**Comment by gdgate** [comment]
Build succeeded (check pipeline).

**Comment by chiendm** [comment]
ok to test

**Comment by gdgate** [comment]
Build failed (check pipeline).

- https://cing-dev.intgdc.com/job/chienmd/job/testing-in-parallel-zuul/1/ : FAILURE in 0s

**Comment by chiendm** [comment]
ok to test

**Comment by gdgate** [comment]
Build failed (check pipeline).

- https://cing-dev.intgdc.com/job/chienmd/job/testing-in-parallel-zuul/2/ : FAILURE in 2m 07s

**Comment by chiendm** [comment]
ok to test

**Comment by gdgate** [comment]
Build succeeded (check pipeline).

- https://cing-dev.intgdc.com/job/chienmd/job/always-success/3/ : SUCCESS in 0s

**Comment by gdgate** [comment]
Build failed (gate pipeline).

- https://cing-dev.intgdc.com/job/chienmd/job/testing-in-parallel-zuul/4/ : FAILURE in 1s

**Comment by gdgate** [comment]
Build failed (gate pipeline).

- https://cing-dev.intgdc.com/job/chienmd/job/testing-in-parallel-zuul/8/ : FAILURE in 5m 22s

**Pull request closed without merging**
