### PR TITLE
dummy.py

### PR DESCRIPTION
**Pull request by caohhung**

### CODE REVIEW

**Comment by gdgate** [comment]
Build succeeded (check pipeline).

- https://cing-dev.intgdc.com/job/compliance/job/jenkins-job-builder-sonarqube-scan-zuul-el7/12/ : SUCCESS in 25s

**Comment by caohhung** [comment]
ok to test

**Comment by gdgate** [comment]
Build succeeded (check pipeline).

- https://cing-dev.intgdc.com/job/compliance/job/jenkins-job-builder-sonarqube-scan-zuul-el7/13/ : SUCCESS in 36s

**Comment by caohhung** [comment]
ok to test

**Comment by gdgate** [comment]
Build succeeded (check pipeline).

- https://cing-dev.intgdc.com/job/compliance/job/jenkins-job-builder-sonarqube-scan-zuul-el7/14/ : SUCCESS in 26s

**Comment by caohhung** [comment]
ok to test

**Comment by gdgate** [comment]
Build succeeded (check pipeline).

- https://cing-dev.intgdc.com/job/compliance/job/jenkins-job-builder-sonarqube-scan-zuul-el7/15/ : SUCCESS in 33s

**Comment by caohhung** [comment]
ok to test

**Comment by gdgate** [comment]
Build succeeded (check pipeline).

- https://cing-dev.intgdc.com/job/compliance/job/jenkins-job-builder-sonarqube-scan-zuul-el7/27/ : SUCCESS in 25s

**Comment by gdgate** [comment]
Build succeeded (check pipeline).

- https://cing-dev.intgdc.com/job/compliance/job/jenkins-job-builder-sonarqube-scan-zuul-el7/33/ : SUCCESS in 26s

**Comment by yenkins** [comment]
'CODE_SMELL': 4, 'BUG': 2

**Comment by yenkins** [comment]
Sonar scan result - 'CODE_SMELL': 4, 'BUG': 2 \n
    More detail, see in https://sonarqube-dev.intgdc.com/dashboard?id=test-zuul-dev-check-PR117-11

**Comment by yenkins** [comment]
Sonar scan result - 'CODE_SMELL': 4, 'BUG': 2
        More detail, see in https://sonarqube-dev.intgdc.com/dashboard?id=test-zuul-dev-check-PR117-12

**Comment by yenkins** [comment]
Sonar scan result - **'CODE_SMELL': 4, 'BUG': 2**
        More detail, see in https://sonarqube-dev.intgdc.com/dashboard?id=test-zuul-dev-check-PR117-13

**Comment by yenkins** [comment]
Sonar scan result - **CODE_SMELL: 4, BUG: 2**
        More detail, see in https://sonarqube-dev.intgdc.com/dashboard?id=test-zuul-dev-check-PR117-15

**Comment by yenkins** [comment]
Sonar scan result - **CODE_SMELL: 4, BUG: 2**
        More detail, see in https://sonarqube-dev.intgdc.com/dashboard?id=test-zuul-dev-check-PR117-18

**Comment by yenkins** [comment]
Sonar scan result - **CODE_SMELL: 4, BUG: 2**
        More detail, see in https://sonarqube-dev.intgdc.com/dashboard?id=test-zuul-dev-check-PR117-19

**Comment by yenkins** [comment]
Sonar scan result - **CODE_SMELL: 4, BUG: 2**
        More detail, see in https://sonarqube-dev.intgdc.com/dashboard?id=test-zuul-dev-check-PR117-20

**Comment by yenkins** [comment]
Sonar scan result - **CODE_SMELL: 4, BUG: 2**
        More detail, see in https://sonarqube-dev.intgdc.com/dashboard?id=test-zuul-dev-check-PR117-21

**Comment by yenkins** [comment]
Sonar scan result - **CODE_SMELL: 4, BUG: 2**
        More detail, see in https://sonarqube-dev.intgdc.com/dashboard?id=test-zuul-dev-check-PR117-22

**Comment by yenkins** [comment]
Sonar scan result - **CODE_SMELL: 4, BUG: 2**
        More detail, see in https://sonarqube-dev.intgdc.com/dashboard?id=test-zuul-dev-check-PR117-23

**Comment by yenkins** [comment]
Sonar scan result - **CODE_SMELL: 4, BUG: 2**
        More detail, see in https://sonarqube-dev.intgdc.com/dashboard?id=test-zuul-dev-check-PR117-24

**Comment by yenkins** [comment]
Sonar scan result - **CODE_SMELL: 4, BUG: 2**
        More detail, see in https://sonarqube-dev.intgdc.com/dashboard?id=test-zuul-dev-check-PR117-25

**Comment by yenkins** [comment]
Sonar scan result - **CODE_SMELL: 4, BUG: 2**
        More detail, see in https://sonarqube-dev.intgdc.com/dashboard?id=test-zuul-dev-check-PR117-26

**Comment by yenkins** [comment]
Sonar scan result - **CODE_SMELL: 4, BUG: 2**
        More detail, see in https://sonarqube-dev.intgdc.com/dashboard?id=test-zuul-dev-check-PR117-27

**Comment by caohhung** [comment]
extended test sonar

**Comment by gdgate** [comment]
Build failed (check-extended pipeline).

- https://cing-dev.intgdc.com/job/compliance/job/jenkins-job-builder-sonarqube-scan-zuul-el7/56/ : FAILURE in 27s

**Comment by gdgate** [comment]
Build succeeded (check pipeline).

**Comment by caohhung** [comment]
extended test sonar

**Comment by gdgate** [comment]
Build failed (check-extended pipeline).

- https://cing-dev.intgdc.com/job/compliance/job/jenkins-job-builder-sonarqube-scan-zuul-el7/57/ : FAILURE in 27s

**Comment by gdgate** [comment]
Build succeeded (check pipeline).

**Comment by caohhung** [comment]
extended test sonar

**Comment by gdgate** [comment]
Build failed (check-extended pipeline).

- https://cing-dev.intgdc.com/job/compliance/job/jenkins-job-builder-sonarqube-scan-zuul-el7/58/ : FAILURE in 27s

**Comment by gdgate** [comment]
Build succeeded (check pipeline).

**Comment by caohhung** [comment]
extended test sonar

**Comment by gdgate** [comment]
Build failed (check-extended pipeline).

- https://cing-dev.intgdc.com/job/compliance/job/jenkins-job-builder-sonarqube-scan-zuul-el7/59/ : FAILURE in 27s

**Comment by caohhung** [comment]
extended test sonar

**Comment by caohhung** [comment]
Sonar scan result - ** 3 BUG	 4 CODE_SMELL	**
        More detail, see in https://sonarqube-dev.intgdc.com/dashboard?id=test-zuul-dev-check-extended-sonar-PR117

**Comment by gdgate** [comment]
Build failed (check-extended pipeline).

- https://cing-dev.intgdc.com/job/compliance/job/jenkins-job-builder-sonarqube-scan-zuul-el7/61/ : FAILURE in 27s

**Comment by caohhung** [comment]
Sonar scan result - ** 3 BUG	 4 CODE_SMELL	**
        More detail, see in https://sonarqube-dev.intgdc.com/dashboard?id=test-zuul-dev-check-extended-sonar-PR117

**Comment by caohhung** [comment]
Sonar scan result - **3 BUG	 4 CODE_SMELL	**
        More detail, see in https://sonarqube-dev.intgdc.com/dashboard?id=test-zuul-dev-check-extended-sonar-PR117

**Comment by caohhung** [comment]
Sonar scan result - **3 BUG -  4 CODE_SMELL**
        More detail, see in https://sonarqube-dev.intgdc.com/dashboard?id=test-zuul-dev-check-extended-sonar-PR117

**Comment by caohhung** [comment]
extended test sonar

**Comment by gdgate** [comment]
Build failed (check-extended pipeline).

- https://cing-dev.intgdc.com/job/compliance/job/jenkins-job-builder-sonarqube-scan-zuul-el7/65/ : FAILURE in 27s

**Comment by caohhung** [comment]
extended test sonar

**Comment by gdgate** [comment]
Build failed (check-extended pipeline).

- https://cing-dev.intgdc.com/job/compliance/job/jenkins-job-builder-sonarqube-scan-zuul-el7/66/ : FAILURE in 32s

**Comment by caohhung** [comment]
extended test sonar

**Comment by caohhung** [comment]
Sonar scan result - ** - 3 BUG
 - 4 CODE_SMELL**
        More detail, see in https://sonarqube-dev.intgdc.com/dashboard?id=test-zuul-dev-check-extended-sonar-PR117

**Comment by gdgate** [comment]
Build failed (check-extended pipeline).

- https://cing-dev.intgdc.com/job/compliance/job/jenkins-job-builder-sonarqube-scan-zuul-el7/67/ : FAILURE in 27s

**Comment by caohhung** [comment]
extended test sonar

**Comment by caohhung** [comment]
Sonar scan result - 
         - 3 BUG
 - 4 CODE_SMELL
        More detail, see in https://sonarqube-dev.intgdc.com/dashboard?id=test-zuul-dev-check-extended-sonar-PR117

**Comment by gdgate** [comment]
Build failed (check-extended pipeline).

- https://cing-dev.intgdc.com/job/compliance/job/jenkins-job-builder-sonarqube-scan-zuul-el7/68/ : FAILURE in 26s

**Comment by caohhung** [comment]
extended test sonar

**Comment by caohhung** [comment]
Sonar scan result -      - 3 BUG
 - 4 CODE_SMELL     More detail, see in https://sonarqube-dev.intgdc.com/dashboard?id=test-zuul-dev-check-extended-sonar-PR117

**Comment by gdgate** [comment]
Build failed (check-extended pipeline).

- https://cing-dev.intgdc.com/job/compliance/job/jenkins-job-builder-sonarqube-scan-zuul-el7/69/ : FAILURE in 27s

**Comment by caohhung** [comment]
extended test sonar

**Comment by caohhung** [comment]
Sonar scan result - \n\n      - 3 BUG
 - 4 CODE_SMELL     More detail, see in https://sonarqube-dev.intgdc.com/dashboard?id=test-zuul-dev-check-extended-sonar-PR117

**Comment by gdgate** [comment]
Build failed (check-extended pipeline).

- https://cing-dev.intgdc.com/job/compliance/job/jenkins-job-builder-sonarqube-scan-zuul-el7/70/ : FAILURE in 28s

**Comment by caohhung** [comment]
extended test sonar

**Comment by caohhung** [comment]
Sonar scan result - \n\n      - 3 BUG
 - 4 CODE_SMELL     More detail, see in https://sonarqube-dev.intgdc.com/dashboard?id=test-zuul-dev-check-extended-sonar-PR117

**Comment by gdgate** [comment]
Build failed (check-extended pipeline).

- https://cing-dev.intgdc.com/job/compliance/job/jenkins-job-builder-sonarqube-scan-zuul-el7/71/ : FAILURE in 27s

**Comment by caohhung** [comment]
extended test sonar

**Comment by caohhung** [comment]
Sonar scan result:      - 3 BUG
 - 4 CODE_SMELL
    More detail, see in https://sonarqube-dev.intgdc.com/dashboard?id=test-zuul-dev-check-extended-sonar-PR117

**Comment by gdgate** [comment]
Build failed (check-extended pipeline).

- https://cing-dev.intgdc.com/job/compliance/job/jenkins-job-builder-sonarqube-scan-zuul-el7/72/ : FAILURE in 27s

**Comment by caohhung** [comment]
extended test sonar

**Comment by caohhung** [comment]
Sonar scan result:      - 3 BUG
 - 4 CODE_SMELL
    More detail, see in https://sonarqube-dev.intgdc.com/dashboard?id=test-zuul-dev-check-extended-sonar-PR117

**Comment by gdgate** [comment]
Build failed (check-extended pipeline).

- https://cing-dev.intgdc.com/job/compliance/job/jenkins-job-builder-sonarqube-scan-zuul-el7/73/ : FAILURE in 27s

**Comment by caohhung** [comment]
extended test sonar

**Comment by caohhung** [comment]
Sonar scan result: 
     - 3 BUG
 - 4 CODE_SMELL
    More detail, see in https://sonarqube-dev.intgdc.com/dashboard?id=test-zuul-dev-check-extended-sonar-PR117

**Comment by gdgate** [comment]
Build failed (check-extended pipeline).

- https://cing-dev.intgdc.com/job/compliance/job/jenkins-job-builder-sonarqube-scan-zuul-el7/74/ : FAILURE in 27s

**Comment by caohhung** [comment]
extended test sonar

**Comment by gdgate** [comment]
Build failed (check-extended pipeline).

- https://cing-dev.intgdc.com/job/compliance/job/jenkins-job-builder-sonarqube-scan-zuul-el7/75/ : FAILURE in 25s

**Comment by caohhung** [comment]
extended test sonar

**Comment by caohhung** [comment]
###Sonar scan result: 
 - 3 BUG
 - 4 CODE_SMELL
More detail, see in

**Comment by gdgate** [comment]
Build failed (check-extended pipeline).

- https://cing-dev.intgdc.com/job/compliance/job/jenkins-job-builder-sonarqube-scan-zuul-el7/76/ : FAILURE in 27s

**Comment by caohhung** [comment]
extended test sonar

**Comment by caohhung** [comment]
### Sonar scan result 
 - 3 BUG
 - 4 CODE_SMELL
More detail, see in https://sonarqube-dev.intgdc.com/dashboard?id=test-zuul-dev-check-extended-sonar-PR117

**Comment by gdgate** [comment]
Build failed (check-extended pipeline).

- https://cing-dev.intgdc.com/job/compliance/job/jenkins-job-builder-sonarqube-scan-zuul-el7/77/ : FAILURE in 27s

**Comment by caohhung** [comment]
extended test sonar

**Comment by caohhung** [comment]
### Sonar scan result 
  - 3 BUG
 - 4 CODE_SMELL 

More detail, see in https://sonarqube-dev.intgdc.com/dashboard?id=test-zuul-dev-check-extended-sonar-PR117

**Comment by gdgate** [comment]
Build failed (check-extended pipeline).

- https://cing-dev.intgdc.com/job/compliance/job/jenkins-job-builder-sonarqube-scan-zuul-el7/78/ : FAILURE in 27s

**Comment by caohhung** [comment]
extended test sonar

**Comment by caohhung** [comment]
### Sonar scan result 
  - 3 BUG
 - 4 CODE_SMELL 

More detail, see in https://sonarqube-dev.intgdc.com/dashboard?id=test-zuul-dev-check-extended-sonar-PR117

**Comment by gdgate** [comment]
Build failed (check-extended pipeline).

- https://cing-dev.intgdc.com/job/compliance/job/jenkins-job-builder-sonarqube-scan-zuul-el7/81/ : FAILURE in 34s

**Comment by caohhung** [comment]
extended test sonar

**Comment by gdgate** [comment]
Build failed (check-extended pipeline).

- https://cing-dev.intgdc.com/job/compliance/job/jenkins-job-builder-sonarqube-scan-zuul-el7/83/ : FAILURE in 6s

**Comment by caohhung** [comment]
extended test sonar

**Comment by caohhung** [comment]
### Sonar scan result 
  - 3 BUG
 - 4 CODE_SMELL 

More detail, see in https://sonarqube-dev.intgdc.com/dashboard?id=test-zuul-dev-check-extended-sonar-PR117

**Comment by gdgate** [comment]
Build failed (check-extended pipeline).

- https://cing-dev.intgdc.com/job/compliance/job/jenkins-job-builder-sonarqube-scan-zuul-el7/85/ : FAILURE in 34s

**Pull request closed without merging**
