### PR TITLE
PR B based on A

### PR DESCRIPTION
**Pull request by chiendm**
Test new gearman plugin version

### CODE REVIEW

**Comment by gdgate** [comment]
Build succeeded (check pipeline).

**Comment by chiendm** [comment]
ok to test

**Comment by gdgate** [comment]
Build succeeded (check pipeline).

**Comment by chiendm** [comment]
ok to test

**Comment by gdgate** [comment]
Build succeeded (check pipeline).

- https://cing-dev.intgdc.com/job/ci/job/update-ci-infra-local-repo/4/ : SUCCESS in 1s

**Comment by chiendm** [comment]
ok to test

**Comment by gdgate** [comment]
Build succeeded (check pipeline).

**Comment by chiendm** [comment]
ok to test

**Comment by gdgate** [comment]
Build succeeded (check pipeline).

**Comment by helobinvn** [comment]
ok to test

**Comment by gdgate** [comment]
Build succeeded (check pipeline).

**Comment by chiendm** [comment]
ok to test

**Comment by gdgate** [comment]
Build succeeded (check pipeline).

- https://cing-dev.intgdc.com/job/ci/job/update-ci-infra-local-repo/7/ : SUCCESS in 16m 41s

**Comment by chiendm** [comment]
ok to test

**Comment by gdgate** [comment]
Build succeeded (check pipeline).

- https://cing-dev.intgdc.com/job/ci/job/update-ci-infra-local-repo/9/ : SUCCESS in 16m 45s

**Comment by chiendm** [comment]
ok to test

**Comment by gdgate** [comment]
Build succeeded (check pipeline).

- https://cing-dev.intgdc.com/job/ci/job/update-ci-infra-local-repo/12/ : SUCCESS in 16m 41s

**Comment by chiendm** [comment]
ok to test

**Comment by gdgate** [comment]
Build succeeded (check pipeline).

- https://cing-dev.intgdc.com/job/ci/job/update-ci-infra-local-repo/17/ : SUCCESS in 16m 42s

**Comment by chiendm** [comment]
ok to test

**Comment by gdgate** [comment]
Build succeeded (check pipeline).

- https://cing-dev.intgdc.com/job/ci/job/update-ci-infra-local-repo/20/ : SUCCESS in 16m 41s

**Comment by chiendm** [comment]
ok to test

**Comment by gdgate** [comment]
Build failed (check pipeline).

- https://cing-dev.intgdc.com/job/ci/job/update-ci-infra-local-repo/23/ : ABORTED in 44s

**Comment by chiendm** [comment]
ok to test

**Comment by gdgate** [comment]
Build succeeded (check pipeline).

- https://cing-dev.intgdc.com/job/ci/job/update-ci-infra-local-repo/25/ : SUCCESS in 16m 41s

**Comment by chiendm** [comment]
ok to test

**Comment by gdgate** [comment]
Build failed (check pipeline).

- https://cing-dev.intgdc.com/job/ci/job/update-ci-infra-local-repo/29/ : ABORTED in 15s

**Comment by chiendm** [comment]
ok to test

**Comment by gdgate** [comment]
Build failed (check pipeline).

- https://cing-dev.intgdc.com/job/ci/job/update-ci-infra-local-repo/32/ : ABORTED in 12s

**Comment by chiendm** [comment]
ok to test

**Comment by gdgate** [comment]
Build failed (check pipeline).

- https://cing-dev.intgdc.com/job/ci/job/update-ci-infra-local-repo/35/ : ABORTED in 2m 35s

**Comment by chiendm** [comment]
ok to test

**Comment by gdgate** [comment]
Build succeeded (check pipeline).

- https://cing-dev.intgdc.com/job/ci/job/update-ci-infra-local-repo/38/ : SUCCESS in 16m 41s

**Comment by chiendm** [comment]
ok to test

**Comment by gdgate** [comment]
Build succeeded (check pipeline).

- https://cing-dev.intgdc.com/job/ci/job/update-ci-infra-local-repo/43/ : SUCCESS in 16m 41s

**Comment by chiendm** [comment]
ok to test

**Comment by gdgate** [comment]
Build succeeded (check pipeline).

- https://cing-dev.intgdc.com/job/ci/job/update-ci-infra-local-repo/45/ : SUCCESS in 16m 41s

**Comment by chiendm** [comment]
ok to test

**Comment by gdgate** [comment]
Build succeeded (check pipeline).

**Comment by chiendm** [comment]
ok to test

**Comment by gdgate** [comment]
Build succeeded (check pipeline).

**Comment by helobinvn** [comment]
ok to test

**Comment by gdgate** [comment]
Build succeeded (check pipeline).

**Comment by helobinvn** [comment]
ok to test

**Comment by gdgate** [comment]
Build failed (check pipeline).

- https://cing-dev.intgdc.com/job/ci/job/update-ci-infra-local-repo/54/ : ABORTED in 12m 56s

**Comment by helobinvn** [comment]
ok to test

**Comment by gdgate** [comment]
Build failed (check pipeline).

- https://cing-dev.intgdc.com/job/ci/job/update-ci-infra-local-repo/57/ : ABORTED in 23s

**Comment by helobinvn** [comment]
ok to test

**Comment by gdgate** [comment]
Build failed (check pipeline).

- https://cing-dev.intgdc.com/job/ci/job/update-ci-infra-local-repo/64/ : ABORTED in 1m 54s

**Comment by helobinvn** [comment]
ok to test

**Comment by gdgate** [comment]
Build failed (check pipeline).

- https://cing-dev.intgdc.com/job/ci/job/update-ci-infra-local-repo/71/ : ABORTED in 7m 24s

**Comment by gdgate** [comment]
Build succeeded (check pipeline).

**Comment by chiendm** [comment]
ok to test

**Comment by gdgate** [comment]
Build failed (check pipeline).

- https://cing-dev.intgdc.com/job/chienmd/job/testing-in-parallel-zuul/3/ : FAILURE in 2m 17s

**Comment by chiendm** [comment]
ok to test

**Comment by gdgate** [comment]
Build succeeded (check pipeline).

- https://cing-dev.intgdc.com/job/chienmd/job/always-success/2/ : SUCCESS in 0s

**Comment by gdgate** [comment]
Build failed (gate pipeline).

- https://cing-dev.intgdc.com/job/chienmd/job/testing-in-parallel-zuul/5/ : FAILURE in 0s

**Comment by gdgate** [comment]
Build failed (gate pipeline).

- https://cing-dev.intgdc.com/job/chienmd/job/testing-in-parallel-zuul/6/ : FAILURE in 5m 06s

**Pull request closed without merging**
