### PR TITLE
fix up

### PR DESCRIPTION
**Pull request by helobinvn**

### CODE REVIEW

**Comment by helobinvn** [comment]
ok to test

**Comment by helobinvn** [comment]
ok to test

**Comment by helobinvn** [comment]
ok to test

**Comment by helobinvn** [comment]
ok to test

**Comment by helobinvn** [comment]
ok to test

**Comment by helobinvn** [comment]
ok to test

**Comment by gdgate** [comment]
Build succeeded (check pipeline).

**Comment by helobinvn** [comment]
ok to test

**Comment by gdgate** [comment]
Build succeeded (check pipeline).

**Comment by helobinvn** [comment]
ok to test

**Comment by gdgate** [comment]
Build succeeded (check pipeline).

**Comment by gdgate** [comment]
Build succeeded (check pipeline).

- https://cing-dev.intgdc.com/job/bp/job/Test-zuul-cloner-cing/1/ : SUCCESS in 0s

**Comment by helobinvn** [comment]
ok to test

**Comment by helobinvn** [comment]
ok to test

**Comment by gdgate** [comment]
Build succeeded (check pipeline).

- https://cing-dev.intgdc.com/job/bp/job/Test-zuul-cloner-cing/3/ : SUCCESS in 5m 00s

**Comment by helobinvn** [comment]
ok to test

**Comment by gdgate** [comment]
Build failed (check pipeline).

- https://cing-dev.intgdc.com/job/bp/job/Test-zuul-cloner-cing/17/ : ABORTED in 4m 32s

**Comment by helobinvn** [comment]
ok to test

**Comment by gdgate** [comment]
Build succeeded (check pipeline).

- https://cing-dev.intgdc.com/job/bp/job/Test-zuul-cloner-cing/18/ : SUCCESS in 5m 00s

**Comment by helobinvn** [comment]
ok to test

**Comment by gdgate** [comment]
Build failed (check pipeline).

- https://cing-dev.intgdc.com/job/bp/job/Test-zuul-cloner-cing/19/ : ABORTED in 1m 39s

**Comment by chiendm** [comment]
ok to test

**Comment by chiendm** [comment]
ok to test

**Comment by gdgate** [comment]
Build succeeded (check pipeline).

- https://cing-dev.intgdc.com/job/ci/job/update-ci-infra-local-repo/11/ : SUCCESS in 16m 42s
- https://cing-dev.intgdc.com/job/bp/job/Test-zuul-cloner-cing/26/ : SUCCESS in 5m 00s

**Comment by chiendm** [comment]
ok to test

**Comment by gdgate** [comment]
Build failed (check pipeline).

- https://cing-dev.intgdc.com/job/ci/job/update-ci-infra-local-repo/14/ : ABORTED in 11s
- https://cing-dev.intgdc.com/job/bp/job/Test-zuul-cloner-cing/28/ : SUCCESS in 5m 00s

**Comment by chiendm** [comment]
ok to test

**Comment by gdgate** [comment]
Build failed (check pipeline).

- https://cing-dev.intgdc.com/job/ci/job/update-ci-infra-local-repo/16/ : ABORTED in 10s
- https://cing-dev.intgdc.com/job/bp/job/Test-zuul-cloner-cing/31/ : ABORTED in 33s

**Comment by chiendm** [comment]
ok to test

**Comment by gdgate** [comment]
Build failed (check pipeline).

- https://cing-dev.intgdc.com/job/ci/job/update-ci-infra-local-repo/18/ : ABORTED in 23s
- https://cing-dev.intgdc.com/job/bp/job/Test-zuul-cloner-cing/32/ : ABORTED in 3m 07s

**Comment by chiendm** [comment]
ok to test

**Comment by gdgate** [comment]
Build failed (check pipeline).

- https://cing-dev.intgdc.com/job/ci/job/update-ci-infra-local-repo/22/ : ABORTED in 12s
- https://cing-dev.intgdc.com/job/bp/job/Test-zuul-cloner-cing/33/ : ABORTED in 2m 20s

**Comment by chiendm** [comment]
ok to test

**Comment by gdgate** [comment]
Build failed (check pipeline).

- https://cing-dev.intgdc.com/job/ci/job/update-ci-infra-local-repo/24/ : ABORTED in 36s
- https://cing-dev.intgdc.com/job/bp/job/Test-zuul-cloner-cing/34/ : ABORTED in 36s

**Comment by chiendm** [comment]
ok to test

**Comment by gdgate** [comment]
Build succeeded (check pipeline).

- https://cing-dev.intgdc.com/job/ci/job/update-ci-infra-local-repo/27/ : SUCCESS in 16m 41s
- https://cing-dev.intgdc.com/job/bp/job/Test-zuul-cloner-cing/35/ : SUCCESS in 5m 00s

**Comment by chiendm** [comment]
ok to test

**Comment by gdgate** [comment]
Build failed (check pipeline).

- https://cing-dev.intgdc.com/job/ci/job/update-ci-infra-local-repo/30/ : ABORTED in 6s
- https://cing-dev.intgdc.com/job/bp/job/Test-zuul-cloner-cing/36/ : ABORTED in 11s

**Comment by chiendm** [comment]
ok to test

**Comment by gdgate** [comment]
Build failed (check pipeline).

- https://cing-dev.intgdc.com/job/ci/job/update-ci-infra-local-repo/33/ : ABORTED in 6s
- https://cing-dev.intgdc.com/job/bp/job/Test-zuul-cloner-cing/37/ : ABORTED in 8s

**Comment by chiendm** [comment]
ok to test

**Comment by gdgate** [comment]
Build failed (check pipeline).

- https://cing-dev.intgdc.com/job/ci/job/update-ci-infra-local-repo/36/ : ABORTED in 5s
- https://cing-dev.intgdc.com/job/bp/job/Test-zuul-cloner-cing/38/ : ABORTED in 2m 21s

**Comment by chiendm** [comment]
ok to test

**Comment by gdgate** [comment]
Build succeeded (check pipeline).

- https://cing-dev.intgdc.com/job/ci/job/update-ci-infra-local-repo/39/ : SUCCESS in 16m 41s
- https://cing-dev.intgdc.com/job/bp/job/Test-zuul-cloner-cing/39/ : SUCCESS in 5m 00s

**Comment by chiendm** [comment]
ok to test

**Comment by gdgate** [comment]
Build succeeded (check pipeline).

- https://cing-dev.intgdc.com/job/ci/job/update-ci-infra-local-repo/42/ : SUCCESS in 16m 41s
- https://cing-dev.intgdc.com/job/bp/job/Test-zuul-cloner-cing/40/ : SUCCESS in 5m 00s

**Comment by chiendm** [comment]
ok to test

**Comment by gdgate** [comment]
Build succeeded (check pipeline).

- https://cing-dev.intgdc.com/job/ci/job/update-ci-infra-local-repo/46/ : SUCCESS in 16m 41s
- https://cing-dev.intgdc.com/job/bp/job/Test-zuul-cloner-cing/41/ : SUCCESS in 5m 00s

**Comment by chiendm** [comment]
ok to test

**Comment by gdgate** [comment]
Build succeeded (check pipeline).

- https://cing-dev.intgdc.com/job/bp/job/Test-zuul-cloner-cing/42/ : SUCCESS in 5m 00s

**Comment by helobinvn** [comment]
ok to test

**Comment by gdgate** [comment]
Build failed (check pipeline).

- https://cing-dev.intgdc.com/job/ci/job/update-ci-infra-local-repo/52/ : ABORTED in 13s

**Comment by helobinvn** [comment]
ok to test

**Comment by gdgate** [comment]
Build failed (check pipeline).

- https://cing-dev.intgdc.com/job/ci/job/update-ci-infra-local-repo/58/ : ABORTED in 32s

**Comment by helobinvn** [comment]
ok to test

**Comment by gdgate** [comment]
Build failed (check pipeline).

- https://cing-dev.intgdc.com/job/ci/job/update-ci-infra-local-repo/65/ : ABORTED in 1m 51s

**Comment by helobinvn** [comment]
ok to test

**Comment by gdgate** [comment]
Build failed (check pipeline).

- https://cing-dev.intgdc.com/job/ci/job/update-ci-infra-local-repo/69/ : ABORTED in 7m 23s

**Comment by caohhung** [comment]
ok to test

**Comment by gdgate** [comment]
Build failed (check pipeline).

- Test-zuul-cloner-cing : NOT_REGISTERED

**Comment by caohhung** [comment]
ok to test

**Comment by gdgate** [comment]
Build failed (check pipeline).

- jenkins-job-builder-sonar-zuul-el7 : NOT_REGISTERED

**Comment by caohhung** [comment]
ok to test

**Comment by gdgate** [comment]
Build failed (check pipeline).

- jenkins-job-builder-sonarqube-scan-zuul-el7 : NOT_REGISTERED

**Comment by caohhung** [comment]
ok to test

**Comment by gdgate** [comment]
Build succeeded (check pipeline).

- https://cing-dev.intgdc.com/job/compliance/job/jenkins-job-builder-sonarqube-scan-zuul-el7/11/ : SUCCESS in 17s

**Comment by helobinvn** [comment]
ok to test

**Comment by gdgate** [comment]
Merge Failed.

Zuul merger could not merge this change into the base branch. This is most likely caused by merge conflicts. Please rebase the change and upload the rebased version. In case of further errors, contact the zuul administrator.

**Comment by gdgate** [comment]
Build succeeded (check pipeline).

**Comment by helobinvn** [comment]
ok to test

**Comment by gdgate** [comment]
Build succeeded (check pipeline).

**Comment by daovietduy99** [comment]
ok to test

**Comment by gdgate** [comment]
Build succeeded (check pipeline).

**Comment by daovietduy99** [comment]
ok to test

**Comment by gdgate** [comment]
Build succeeded (check pipeline).

**Comment by ghost** [comment]
Build succeeded (gate pipeline).

**Comment by yenkins** [comment]
ok to test

**Comment by ghost** [comment]
Build succeeded (check pipeline).

**Pull request merged**
