### PR TITLE
FEATURE: ROD-4121 test PR

### PR DESCRIPTION
**Pull request by pcerny**

### CODE REVIEW

**Comment by gdgate** [comment]
Build succeeded (check pipeline).

**Comment by pcerny** [comment]
ok to test

**Comment by gdgate** [comment]
Build succeeded (check pipeline).

**Comment by gdgate** [comment]
Build succeeded (check pipeline).

**Comment by pcerny** [comment]
ok to test

**Comment by pcerny** [comment]
ok to test

**Comment by gdgate** [comment]
Build succeeded (check pipeline).

- https://cing-dev.intgdc.com/job/zuul-test/job/zuul-test-test-build-set-ts-src/1/ : SUCCESS in 0s
- https://cing-dev.intgdc.com/job/zuul-test/job/zuul-test-test-build-set-ts-dst/2/ : SUCCESS in 0s

**Comment by pcerny** [comment]
ok to test

**Comment by gdgate** [comment]
Build succeeded (check pipeline).

- https://cing-dev.intgdc.com/job/zuul-test/job/zuul-test-test-build-set-ts-src/2/ : SUCCESS in 0s
- https://cing-dev.intgdc.com/job/zuul-test/job/zuul-test-test-build-set-ts-dst/3/ : SUCCESS in 0s

**Comment by pcerny** [comment]
ok to test

**Comment by gdgate** [comment]
Build succeeded (check pipeline).

- https://cing-dev.intgdc.com/job/zuul-test/job/zuul-test-test-build-set-ts-src/3/ : SUCCESS in 0s
- https://cing-dev.intgdc.com/job/zuul-test/job/zuul-test-test-build-set-ts-dst/4/ : SUCCESS in 0s

**Pull request closed without merging**
